// GENERATED by scripts/build-offline-index.mjs — do not edit by hand.
//
// Bible text that ships inside the app: kjv (66 books), twi-akuapem (66 books), twi-asante (66 books).
//
// The KJV is public domain. The Twi editions are Biblica's "Open" editions,
// released under CC BY-SA 4.0 and copied verbatim; the copyright line each
// one requires lives in constants/bible-translations.ts and is shown with the
// text. Bundling them means a reader in Ghana needs no network and no
// account to read scripture in their own language.

type ChapterData = string[][];

export const DEFAULT_TRANSLATION = 'kjv';

const LOADERS: Record<string, Record<string, () => ChapterData>> = {
  'kjv': {
    '1ch': () => require('../assets/bible/kjv/1ch.json'),
    '1co': () => require('../assets/bible/kjv/1co.json'),
    '1jn': () => require('../assets/bible/kjv/1jn.json'),
    '1ki': () => require('../assets/bible/kjv/1ki.json'),
    '1pe': () => require('../assets/bible/kjv/1pe.json'),
    '1sa': () => require('../assets/bible/kjv/1sa.json'),
    '1th': () => require('../assets/bible/kjv/1th.json'),
    '1ti': () => require('../assets/bible/kjv/1ti.json'),
    '2ch': () => require('../assets/bible/kjv/2ch.json'),
    '2co': () => require('../assets/bible/kjv/2co.json'),
    '2jn': () => require('../assets/bible/kjv/2jn.json'),
    '2ki': () => require('../assets/bible/kjv/2ki.json'),
    '2pe': () => require('../assets/bible/kjv/2pe.json'),
    '2sa': () => require('../assets/bible/kjv/2sa.json'),
    '2th': () => require('../assets/bible/kjv/2th.json'),
    '2ti': () => require('../assets/bible/kjv/2ti.json'),
    '3jn': () => require('../assets/bible/kjv/3jn.json'),
    'act': () => require('../assets/bible/kjv/act.json'),
    'amo': () => require('../assets/bible/kjv/amo.json'),
    'col': () => require('../assets/bible/kjv/col.json'),
    'dan': () => require('../assets/bible/kjv/dan.json'),
    'deu': () => require('../assets/bible/kjv/deu.json'),
    'ecc': () => require('../assets/bible/kjv/ecc.json'),
    'eph': () => require('../assets/bible/kjv/eph.json'),
    'est': () => require('../assets/bible/kjv/est.json'),
    'exo': () => require('../assets/bible/kjv/exo.json'),
    'ezk': () => require('../assets/bible/kjv/ezk.json'),
    'ezr': () => require('../assets/bible/kjv/ezr.json'),
    'gal': () => require('../assets/bible/kjv/gal.json'),
    'gen': () => require('../assets/bible/kjv/gen.json'),
    'hab': () => require('../assets/bible/kjv/hab.json'),
    'hag': () => require('../assets/bible/kjv/hag.json'),
    'heb': () => require('../assets/bible/kjv/heb.json'),
    'hos': () => require('../assets/bible/kjv/hos.json'),
    'isa': () => require('../assets/bible/kjv/isa.json'),
    'jas': () => require('../assets/bible/kjv/jas.json'),
    'jdg': () => require('../assets/bible/kjv/jdg.json'),
    'jer': () => require('../assets/bible/kjv/jer.json'),
    'jhn': () => require('../assets/bible/kjv/jhn.json'),
    'job': () => require('../assets/bible/kjv/job.json'),
    'jol': () => require('../assets/bible/kjv/jol.json'),
    'jon': () => require('../assets/bible/kjv/jon.json'),
    'jos': () => require('../assets/bible/kjv/jos.json'),
    'jud': () => require('../assets/bible/kjv/jud.json'),
    'lam': () => require('../assets/bible/kjv/lam.json'),
    'lev': () => require('../assets/bible/kjv/lev.json'),
    'luk': () => require('../assets/bible/kjv/luk.json'),
    'mal': () => require('../assets/bible/kjv/mal.json'),
    'mat': () => require('../assets/bible/kjv/mat.json'),
    'mic': () => require('../assets/bible/kjv/mic.json'),
    'mrk': () => require('../assets/bible/kjv/mrk.json'),
    'nam': () => require('../assets/bible/kjv/nam.json'),
    'neh': () => require('../assets/bible/kjv/neh.json'),
    'num': () => require('../assets/bible/kjv/num.json'),
    'oba': () => require('../assets/bible/kjv/oba.json'),
    'phi': () => require('../assets/bible/kjv/phi.json'),
    'phm': () => require('../assets/bible/kjv/phm.json'),
    'pro': () => require('../assets/bible/kjv/pro.json'),
    'psa': () => require('../assets/bible/kjv/psa.json'),
    'rev': () => require('../assets/bible/kjv/rev.json'),
    'rom': () => require('../assets/bible/kjv/rom.json'),
    'rut': () => require('../assets/bible/kjv/rut.json'),
    'sng': () => require('../assets/bible/kjv/sng.json'),
    'tit': () => require('../assets/bible/kjv/tit.json'),
    'zec': () => require('../assets/bible/kjv/zec.json'),
    'zep': () => require('../assets/bible/kjv/zep.json'),
  },
  'twi-akuapem': {
    '1ch': () => require('../assets/bible/twi-akuapem/1ch.json'),
    '1co': () => require('../assets/bible/twi-akuapem/1co.json'),
    '1jn': () => require('../assets/bible/twi-akuapem/1jn.json'),
    '1ki': () => require('../assets/bible/twi-akuapem/1ki.json'),
    '1pe': () => require('../assets/bible/twi-akuapem/1pe.json'),
    '1sa': () => require('../assets/bible/twi-akuapem/1sa.json'),
    '1th': () => require('../assets/bible/twi-akuapem/1th.json'),
    '1ti': () => require('../assets/bible/twi-akuapem/1ti.json'),
    '2ch': () => require('../assets/bible/twi-akuapem/2ch.json'),
    '2co': () => require('../assets/bible/twi-akuapem/2co.json'),
    '2jn': () => require('../assets/bible/twi-akuapem/2jn.json'),
    '2ki': () => require('../assets/bible/twi-akuapem/2ki.json'),
    '2pe': () => require('../assets/bible/twi-akuapem/2pe.json'),
    '2sa': () => require('../assets/bible/twi-akuapem/2sa.json'),
    '2th': () => require('../assets/bible/twi-akuapem/2th.json'),
    '2ti': () => require('../assets/bible/twi-akuapem/2ti.json'),
    '3jn': () => require('../assets/bible/twi-akuapem/3jn.json'),
    'act': () => require('../assets/bible/twi-akuapem/act.json'),
    'amo': () => require('../assets/bible/twi-akuapem/amo.json'),
    'col': () => require('../assets/bible/twi-akuapem/col.json'),
    'dan': () => require('../assets/bible/twi-akuapem/dan.json'),
    'deu': () => require('../assets/bible/twi-akuapem/deu.json'),
    'ecc': () => require('../assets/bible/twi-akuapem/ecc.json'),
    'eph': () => require('../assets/bible/twi-akuapem/eph.json'),
    'est': () => require('../assets/bible/twi-akuapem/est.json'),
    'exo': () => require('../assets/bible/twi-akuapem/exo.json'),
    'ezk': () => require('../assets/bible/twi-akuapem/ezk.json'),
    'ezr': () => require('../assets/bible/twi-akuapem/ezr.json'),
    'gal': () => require('../assets/bible/twi-akuapem/gal.json'),
    'gen': () => require('../assets/bible/twi-akuapem/gen.json'),
    'hab': () => require('../assets/bible/twi-akuapem/hab.json'),
    'hag': () => require('../assets/bible/twi-akuapem/hag.json'),
    'heb': () => require('../assets/bible/twi-akuapem/heb.json'),
    'hos': () => require('../assets/bible/twi-akuapem/hos.json'),
    'isa': () => require('../assets/bible/twi-akuapem/isa.json'),
    'jas': () => require('../assets/bible/twi-akuapem/jas.json'),
    'jdg': () => require('../assets/bible/twi-akuapem/jdg.json'),
    'jer': () => require('../assets/bible/twi-akuapem/jer.json'),
    'jhn': () => require('../assets/bible/twi-akuapem/jhn.json'),
    'job': () => require('../assets/bible/twi-akuapem/job.json'),
    'jol': () => require('../assets/bible/twi-akuapem/jol.json'),
    'jon': () => require('../assets/bible/twi-akuapem/jon.json'),
    'jos': () => require('../assets/bible/twi-akuapem/jos.json'),
    'jud': () => require('../assets/bible/twi-akuapem/jud.json'),
    'lam': () => require('../assets/bible/twi-akuapem/lam.json'),
    'lev': () => require('../assets/bible/twi-akuapem/lev.json'),
    'luk': () => require('../assets/bible/twi-akuapem/luk.json'),
    'mal': () => require('../assets/bible/twi-akuapem/mal.json'),
    'mat': () => require('../assets/bible/twi-akuapem/mat.json'),
    'mic': () => require('../assets/bible/twi-akuapem/mic.json'),
    'mrk': () => require('../assets/bible/twi-akuapem/mrk.json'),
    'nam': () => require('../assets/bible/twi-akuapem/nam.json'),
    'neh': () => require('../assets/bible/twi-akuapem/neh.json'),
    'num': () => require('../assets/bible/twi-akuapem/num.json'),
    'oba': () => require('../assets/bible/twi-akuapem/oba.json'),
    'phi': () => require('../assets/bible/twi-akuapem/phi.json'),
    'phm': () => require('../assets/bible/twi-akuapem/phm.json'),
    'pro': () => require('../assets/bible/twi-akuapem/pro.json'),
    'psa': () => require('../assets/bible/twi-akuapem/psa.json'),
    'rev': () => require('../assets/bible/twi-akuapem/rev.json'),
    'rom': () => require('../assets/bible/twi-akuapem/rom.json'),
    'rut': () => require('../assets/bible/twi-akuapem/rut.json'),
    'sng': () => require('../assets/bible/twi-akuapem/sng.json'),
    'tit': () => require('../assets/bible/twi-akuapem/tit.json'),
    'zec': () => require('../assets/bible/twi-akuapem/zec.json'),
    'zep': () => require('../assets/bible/twi-akuapem/zep.json'),
  },
  'twi-asante': {
    '1ch': () => require('../assets/bible/twi-asante/1ch.json'),
    '1co': () => require('../assets/bible/twi-asante/1co.json'),
    '1jn': () => require('../assets/bible/twi-asante/1jn.json'),
    '1ki': () => require('../assets/bible/twi-asante/1ki.json'),
    '1pe': () => require('../assets/bible/twi-asante/1pe.json'),
    '1sa': () => require('../assets/bible/twi-asante/1sa.json'),
    '1th': () => require('../assets/bible/twi-asante/1th.json'),
    '1ti': () => require('../assets/bible/twi-asante/1ti.json'),
    '2ch': () => require('../assets/bible/twi-asante/2ch.json'),
    '2co': () => require('../assets/bible/twi-asante/2co.json'),
    '2jn': () => require('../assets/bible/twi-asante/2jn.json'),
    '2ki': () => require('../assets/bible/twi-asante/2ki.json'),
    '2pe': () => require('../assets/bible/twi-asante/2pe.json'),
    '2sa': () => require('../assets/bible/twi-asante/2sa.json'),
    '2th': () => require('../assets/bible/twi-asante/2th.json'),
    '2ti': () => require('../assets/bible/twi-asante/2ti.json'),
    '3jn': () => require('../assets/bible/twi-asante/3jn.json'),
    'act': () => require('../assets/bible/twi-asante/act.json'),
    'amo': () => require('../assets/bible/twi-asante/amo.json'),
    'col': () => require('../assets/bible/twi-asante/col.json'),
    'dan': () => require('../assets/bible/twi-asante/dan.json'),
    'deu': () => require('../assets/bible/twi-asante/deu.json'),
    'ecc': () => require('../assets/bible/twi-asante/ecc.json'),
    'eph': () => require('../assets/bible/twi-asante/eph.json'),
    'est': () => require('../assets/bible/twi-asante/est.json'),
    'exo': () => require('../assets/bible/twi-asante/exo.json'),
    'ezk': () => require('../assets/bible/twi-asante/ezk.json'),
    'ezr': () => require('../assets/bible/twi-asante/ezr.json'),
    'gal': () => require('../assets/bible/twi-asante/gal.json'),
    'gen': () => require('../assets/bible/twi-asante/gen.json'),
    'hab': () => require('../assets/bible/twi-asante/hab.json'),
    'hag': () => require('../assets/bible/twi-asante/hag.json'),
    'heb': () => require('../assets/bible/twi-asante/heb.json'),
    'hos': () => require('../assets/bible/twi-asante/hos.json'),
    'isa': () => require('../assets/bible/twi-asante/isa.json'),
    'jas': () => require('../assets/bible/twi-asante/jas.json'),
    'jdg': () => require('../assets/bible/twi-asante/jdg.json'),
    'jer': () => require('../assets/bible/twi-asante/jer.json'),
    'jhn': () => require('../assets/bible/twi-asante/jhn.json'),
    'job': () => require('../assets/bible/twi-asante/job.json'),
    'jol': () => require('../assets/bible/twi-asante/jol.json'),
    'jon': () => require('../assets/bible/twi-asante/jon.json'),
    'jos': () => require('../assets/bible/twi-asante/jos.json'),
    'jud': () => require('../assets/bible/twi-asante/jud.json'),
    'lam': () => require('../assets/bible/twi-asante/lam.json'),
    'lev': () => require('../assets/bible/twi-asante/lev.json'),
    'luk': () => require('../assets/bible/twi-asante/luk.json'),
    'mal': () => require('../assets/bible/twi-asante/mal.json'),
    'mat': () => require('../assets/bible/twi-asante/mat.json'),
    'mic': () => require('../assets/bible/twi-asante/mic.json'),
    'mrk': () => require('../assets/bible/twi-asante/mrk.json'),
    'nam': () => require('../assets/bible/twi-asante/nam.json'),
    'neh': () => require('../assets/bible/twi-asante/neh.json'),
    'num': () => require('../assets/bible/twi-asante/num.json'),
    'oba': () => require('../assets/bible/twi-asante/oba.json'),
    'phi': () => require('../assets/bible/twi-asante/phi.json'),
    'phm': () => require('../assets/bible/twi-asante/phm.json'),
    'pro': () => require('../assets/bible/twi-asante/pro.json'),
    'psa': () => require('../assets/bible/twi-asante/psa.json'),
    'rev': () => require('../assets/bible/twi-asante/rev.json'),
    'rom': () => require('../assets/bible/twi-asante/rom.json'),
    'rut': () => require('../assets/bible/twi-asante/rut.json'),
    'sng': () => require('../assets/bible/twi-asante/sng.json'),
    'tit': () => require('../assets/bible/twi-asante/tit.json'),
    'zec': () => require('../assets/bible/twi-asante/zec.json'),
    'zep': () => require('../assets/bible/twi-asante/zep.json'),
  },
};

const cache = new Map<string, ChapterData>();

function loadBook(translationId: string, bookId: string): ChapterData | null {
  const key = `${translationId}:${bookId}`;
  const cached = cache.get(key);
  if (cached) return cached;

  const loader = LOADERS[translationId]?.[bookId];
  if (!loader) return null;

  const data = loader();
  cache.set(key, data);
  return data;
}

/**
 * Verse strings for a chapter, or null when the reference does not exist.
 *
 * Defaults to the KJV, which is also what callers use as the fallback when a
 * remote translation cannot be loaded.
 */
export function getOfflineChapter(
  bookId: string,
  chapter: number,
  translationId: string = DEFAULT_TRANSLATION
): string[] | null {
  const book = loadBook(translationId, bookId);
  if (!book) return null;

  const verses = book[chapter - 1] ?? null;
  // A translation may leave a verse number unused where it merges two verses.
  return verses ? verses.filter((verse) => verse.length > 0) : null;
}

export function hasOfflineBook(
  bookId: string,
  translationId: string = DEFAULT_TRANSLATION
): boolean {
  return Boolean(LOADERS[translationId]?.[bookId]);
}

/** True when the whole translation ships with the app. */
export function isBundledTranslation(translationId: string): boolean {
  return translationId in LOADERS;
}
