// GENERATED by scripts/build-bible.mjs — do not edit by hand.
// Offline KJV text (Public Domain). Each entry is [chapter][verseIndex] => string.

type ChapterData = string[][];

const LOADERS: Record<string, () => ChapterData> = {
  'gen': () => require('../assets/bible/kjv/gen.json'),
  'exo': () => require('../assets/bible/kjv/exo.json'),
  'lev': () => require('../assets/bible/kjv/lev.json'),
  'num': () => require('../assets/bible/kjv/num.json'),
  'deu': () => require('../assets/bible/kjv/deu.json'),
  'jos': () => require('../assets/bible/kjv/jos.json'),
  'jdg': () => require('../assets/bible/kjv/jdg.json'),
  'rut': () => require('../assets/bible/kjv/rut.json'),
  '1sa': () => require('../assets/bible/kjv/1sa.json'),
  '2sa': () => require('../assets/bible/kjv/2sa.json'),
  '1ki': () => require('../assets/bible/kjv/1ki.json'),
  '2ki': () => require('../assets/bible/kjv/2ki.json'),
  '1ch': () => require('../assets/bible/kjv/1ch.json'),
  '2ch': () => require('../assets/bible/kjv/2ch.json'),
  'ezr': () => require('../assets/bible/kjv/ezr.json'),
  'neh': () => require('../assets/bible/kjv/neh.json'),
  'est': () => require('../assets/bible/kjv/est.json'),
  'job': () => require('../assets/bible/kjv/job.json'),
  'psa': () => require('../assets/bible/kjv/psa.json'),
  'pro': () => require('../assets/bible/kjv/pro.json'),
  'ecc': () => require('../assets/bible/kjv/ecc.json'),
  'sng': () => require('../assets/bible/kjv/sng.json'),
  'isa': () => require('../assets/bible/kjv/isa.json'),
  'jer': () => require('../assets/bible/kjv/jer.json'),
  'lam': () => require('../assets/bible/kjv/lam.json'),
  'ezk': () => require('../assets/bible/kjv/ezk.json'),
  'dan': () => require('../assets/bible/kjv/dan.json'),
  'hos': () => require('../assets/bible/kjv/hos.json'),
  'jol': () => require('../assets/bible/kjv/jol.json'),
  'amo': () => require('../assets/bible/kjv/amo.json'),
  'oba': () => require('../assets/bible/kjv/oba.json'),
  'jon': () => require('../assets/bible/kjv/jon.json'),
  'mic': () => require('../assets/bible/kjv/mic.json'),
  'nam': () => require('../assets/bible/kjv/nam.json'),
  'hab': () => require('../assets/bible/kjv/hab.json'),
  'zep': () => require('../assets/bible/kjv/zep.json'),
  'hag': () => require('../assets/bible/kjv/hag.json'),
  'zec': () => require('../assets/bible/kjv/zec.json'),
  'mal': () => require('../assets/bible/kjv/mal.json'),
  'mat': () => require('../assets/bible/kjv/mat.json'),
  'mrk': () => require('../assets/bible/kjv/mrk.json'),
  'luk': () => require('../assets/bible/kjv/luk.json'),
  'jhn': () => require('../assets/bible/kjv/jhn.json'),
  'act': () => require('../assets/bible/kjv/act.json'),
  'rom': () => require('../assets/bible/kjv/rom.json'),
  '1co': () => require('../assets/bible/kjv/1co.json'),
  '2co': () => require('../assets/bible/kjv/2co.json'),
  'gal': () => require('../assets/bible/kjv/gal.json'),
  'eph': () => require('../assets/bible/kjv/eph.json'),
  'phi': () => require('../assets/bible/kjv/phi.json'),
  'col': () => require('../assets/bible/kjv/col.json'),
  '1th': () => require('../assets/bible/kjv/1th.json'),
  '2th': () => require('../assets/bible/kjv/2th.json'),
  '1ti': () => require('../assets/bible/kjv/1ti.json'),
  '2ti': () => require('../assets/bible/kjv/2ti.json'),
  'tit': () => require('../assets/bible/kjv/tit.json'),
  'phm': () => require('../assets/bible/kjv/phm.json'),
  'heb': () => require('../assets/bible/kjv/heb.json'),
  'jas': () => require('../assets/bible/kjv/jas.json'),
  '1pe': () => require('../assets/bible/kjv/1pe.json'),
  '2pe': () => require('../assets/bible/kjv/2pe.json'),
  '1jn': () => require('../assets/bible/kjv/1jn.json'),
  '2jn': () => require('../assets/bible/kjv/2jn.json'),
  '3jn': () => require('../assets/bible/kjv/3jn.json'),
  'jud': () => require('../assets/bible/kjv/jud.json'),
  'rev': () => require('../assets/bible/kjv/rev.json'),
};

const cache = new Map<string, ChapterData>();

function loadBook(bookId: string): ChapterData | null {
  const cached = cache.get(bookId);
  if (cached) return cached;

  const loader = LOADERS[bookId];
  if (!loader) return null;

  const data = loader();
  cache.set(bookId, data);
  return data;
}

/** Verse strings for a chapter, or null when the reference does not exist. */
export function getOfflineChapter(bookId: string, chapter: number): string[] | null {
  const book = loadBook(bookId);
  if (!book) return null;
  return book[chapter - 1] ?? null;
}

export function hasOfflineBook(bookId: string): boolean {
  return bookId in LOADERS;
}
