// GENERATED by scripts/build-plan-templates.mjs — do not edit by hand.
//
// Starter plans, so the plans screen is not an empty room for someone who has
// just installed the app and knows nobody using it. Every reference below was
// generated from the bundled text, so every day points at a real passage.

export type PlanTemplate = {
  id: string;
  title: string;
  description: string;
  days: { reference: string }[];
};

export const PLAN_TEMPLATES: PlanTemplate[] = [
  {
    "id": "john-21",
    "title": "The Gospel of John in 21 days",
    "description": "One chapter a day through the fourth gospel. A good first plan — three weeks, and you finish something.",
    "days": [
      {
        "reference": "John 1"
      },
      {
        "reference": "John 2"
      },
      {
        "reference": "John 3"
      },
      {
        "reference": "John 4"
      },
      {
        "reference": "John 5"
      },
      {
        "reference": "John 6"
      },
      {
        "reference": "John 7"
      },
      {
        "reference": "John 8"
      },
      {
        "reference": "John 9"
      },
      {
        "reference": "John 10"
      },
      {
        "reference": "John 11"
      },
      {
        "reference": "John 12"
      },
      {
        "reference": "John 13"
      },
      {
        "reference": "John 14"
      },
      {
        "reference": "John 15"
      },
      {
        "reference": "John 16"
      },
      {
        "reference": "John 17"
      },
      {
        "reference": "John 18"
      },
      {
        "reference": "John 19"
      },
      {
        "reference": "John 20"
      },
      {
        "reference": "John 21"
      }
    ]
  },
  {
    "id": "psalms-proverbs-60",
    "title": "Psalms & Proverbs in 60 days",
    "description": "The songbook and the wisdom of Israel, side by side. Short readings, good for a busy season.",
    "days": [
      {
        "reference": "Psalms 1-3"
      },
      {
        "reference": "Psalms 4-6"
      },
      {
        "reference": "Psalms 7-9"
      },
      {
        "reference": "Psalms 10-12"
      },
      {
        "reference": "Psalms 13-15"
      },
      {
        "reference": "Psalms 16-18"
      },
      {
        "reference": "Psalms 19-21"
      },
      {
        "reference": "Psalms 22-24"
      },
      {
        "reference": "Psalms 25-27"
      },
      {
        "reference": "Psalms 28-30"
      },
      {
        "reference": "Psalms 31-33"
      },
      {
        "reference": "Psalms 34-36"
      },
      {
        "reference": "Psalms 37-39"
      },
      {
        "reference": "Psalms 40-42"
      },
      {
        "reference": "Psalms 43-45"
      },
      {
        "reference": "Psalms 46-48"
      },
      {
        "reference": "Psalms 49-51"
      },
      {
        "reference": "Psalms 52-54"
      },
      {
        "reference": "Psalms 55-57"
      },
      {
        "reference": "Psalms 58-60"
      },
      {
        "reference": "Psalms 61-63"
      },
      {
        "reference": "Psalms 64-66"
      },
      {
        "reference": "Psalms 67-69"
      },
      {
        "reference": "Psalms 70-72"
      },
      {
        "reference": "Psalms 73-75"
      },
      {
        "reference": "Psalms 76-78"
      },
      {
        "reference": "Psalms 79-81"
      },
      {
        "reference": "Psalms 82-84"
      },
      {
        "reference": "Psalms 85-87"
      },
      {
        "reference": "Psalms 88-91"
      },
      {
        "reference": "Psalms 92-94"
      },
      {
        "reference": "Psalms 95-97"
      },
      {
        "reference": "Psalms 98-100"
      },
      {
        "reference": "Psalms 101-103"
      },
      {
        "reference": "Psalms 104-106"
      },
      {
        "reference": "Psalms 107-109"
      },
      {
        "reference": "Psalms 110-112"
      },
      {
        "reference": "Psalms 113-115"
      },
      {
        "reference": "Psalms 116-118"
      },
      {
        "reference": "Psalms 119-121"
      },
      {
        "reference": "Psalms 122-124"
      },
      {
        "reference": "Psalms 125-127"
      },
      {
        "reference": "Psalms 128-130"
      },
      {
        "reference": "Psalms 131-133"
      },
      {
        "reference": "Psalms 134-136"
      },
      {
        "reference": "Psalms 137-139"
      },
      {
        "reference": "Psalms 140-142"
      },
      {
        "reference": "Psalms 143-145"
      },
      {
        "reference": "Psalms 146-148"
      },
      {
        "reference": "Psalms 149-150 · Proverbs 1"
      },
      {
        "reference": "Proverbs 2-4"
      },
      {
        "reference": "Proverbs 5-7"
      },
      {
        "reference": "Proverbs 8-10"
      },
      {
        "reference": "Proverbs 11-13"
      },
      {
        "reference": "Proverbs 14-16"
      },
      {
        "reference": "Proverbs 17-19"
      },
      {
        "reference": "Proverbs 20-22"
      },
      {
        "reference": "Proverbs 23-25"
      },
      {
        "reference": "Proverbs 26-28"
      },
      {
        "reference": "Proverbs 29-31"
      }
    ]
  },
  {
    "id": "nt-90",
    "title": "The New Testament in 90 days",
    "description": "Matthew through Revelation in three months. About three chapters a day.",
    "days": [
      {
        "reference": "Matthew 1-3"
      },
      {
        "reference": "Matthew 4-6"
      },
      {
        "reference": "Matthew 7-9"
      },
      {
        "reference": "Matthew 10-12"
      },
      {
        "reference": "Matthew 13-14"
      },
      {
        "reference": "Matthew 15-17"
      },
      {
        "reference": "Matthew 18-20"
      },
      {
        "reference": "Matthew 21-23"
      },
      {
        "reference": "Matthew 24-26"
      },
      {
        "reference": "Matthew 27-28 · Mark 1"
      },
      {
        "reference": "Mark 2-4"
      },
      {
        "reference": "Mark 5-7"
      },
      {
        "reference": "Mark 8-10"
      },
      {
        "reference": "Mark 11-12"
      },
      {
        "reference": "Mark 13-15"
      },
      {
        "reference": "Mark 16 · Luke 1-2"
      },
      {
        "reference": "Luke 3-5"
      },
      {
        "reference": "Luke 6-8"
      },
      {
        "reference": "Luke 9-11"
      },
      {
        "reference": "Luke 12-14"
      },
      {
        "reference": "Luke 15-17"
      },
      {
        "reference": "Luke 18-20"
      },
      {
        "reference": "Luke 21-22"
      },
      {
        "reference": "Luke 23-24 · John 1"
      },
      {
        "reference": "John 2-4"
      },
      {
        "reference": "John 5-7"
      },
      {
        "reference": "John 8-10"
      },
      {
        "reference": "John 11-13"
      },
      {
        "reference": "John 14-16"
      },
      {
        "reference": "John 17-19"
      },
      {
        "reference": "John 20-21 · Acts 1"
      },
      {
        "reference": "Acts 2-3"
      },
      {
        "reference": "Acts 4-6"
      },
      {
        "reference": "Acts 7-9"
      },
      {
        "reference": "Acts 10-12"
      },
      {
        "reference": "Acts 13-15"
      },
      {
        "reference": "Acts 16-18"
      },
      {
        "reference": "Acts 19-21"
      },
      {
        "reference": "Acts 22-24"
      },
      {
        "reference": "Acts 25-27"
      },
      {
        "reference": "Acts 28 · Romans 1"
      },
      {
        "reference": "Romans 2-4"
      },
      {
        "reference": "Romans 5-7"
      },
      {
        "reference": "Romans 8-10"
      },
      {
        "reference": "Romans 11-13"
      },
      {
        "reference": "Romans 14-16"
      },
      {
        "reference": "1 Corinthians 1-3"
      },
      {
        "reference": "1 Corinthians 4-6"
      },
      {
        "reference": "1 Corinthians 7-9"
      },
      {
        "reference": "1 Corinthians 10-11"
      },
      {
        "reference": "1 Corinthians 12-14"
      },
      {
        "reference": "1 Corinthians 15-16 · 2 Corinthians 1"
      },
      {
        "reference": "2 Corinthians 2-4"
      },
      {
        "reference": "2 Corinthians 5-7"
      },
      {
        "reference": "2 Corinthians 8-10"
      },
      {
        "reference": "2 Corinthians 11-13"
      },
      {
        "reference": "Galatians 1-3"
      },
      {
        "reference": "Galatians 4-6"
      },
      {
        "reference": "Ephesians 1-2"
      },
      {
        "reference": "Ephesians 3-5"
      },
      {
        "reference": "Ephesians 6 · Philippians 1-2"
      },
      {
        "reference": "Philippians 3-4 · Colossians 1"
      },
      {
        "reference": "Colossians 2-4"
      },
      {
        "reference": "1 Thessalonians 1-3"
      },
      {
        "reference": "1 Thessalonians 4-5 · 2 Thessalonians 1"
      },
      {
        "reference": "2 Thessalonians 2-3 · 1 Timothy 1"
      },
      {
        "reference": "1 Timothy 2-4"
      },
      {
        "reference": "1 Timothy 5-6"
      },
      {
        "reference": "2 Timothy 1-3"
      },
      {
        "reference": "2 Timothy 4 · Titus 1-2"
      },
      {
        "reference": "Titus 3 · Philemon 1 · Hebrews 1"
      },
      {
        "reference": "Hebrews 2-4"
      },
      {
        "reference": "Hebrews 5-7"
      },
      {
        "reference": "Hebrews 8-10"
      },
      {
        "reference": "Hebrews 11-13"
      },
      {
        "reference": "James 1-3"
      },
      {
        "reference": "James 4-5"
      },
      {
        "reference": "1 Peter 1-3"
      },
      {
        "reference": "1 Peter 4-5 · 2 Peter 1"
      },
      {
        "reference": "2 Peter 2-3 · 1 John 1"
      },
      {
        "reference": "1 John 2-4"
      },
      {
        "reference": "1 John 5 · 2 John 1 · 3 John 1"
      },
      {
        "reference": "Jude 1 · Revelation 1-2"
      },
      {
        "reference": "Revelation 3-5"
      },
      {
        "reference": "Revelation 6-8"
      },
      {
        "reference": "Revelation 9-10"
      },
      {
        "reference": "Revelation 11-13"
      },
      {
        "reference": "Revelation 14-16"
      },
      {
        "reference": "Revelation 17-19"
      },
      {
        "reference": "Revelation 20-22"
      }
    ]
  },
  {
    "id": "bible-365",
    "title": "The Bible in a year",
    "description": "All 66 books, Genesis to Revelation, in 365 days. Roughly three chapters a day.",
    "days": [
      {
        "reference": "Genesis 1-3"
      },
      {
        "reference": "Genesis 4-7"
      },
      {
        "reference": "Genesis 8-10"
      },
      {
        "reference": "Genesis 11-13"
      },
      {
        "reference": "Genesis 14-16"
      },
      {
        "reference": "Genesis 17-20"
      },
      {
        "reference": "Genesis 21-23"
      },
      {
        "reference": "Genesis 24-26"
      },
      {
        "reference": "Genesis 27-29"
      },
      {
        "reference": "Genesis 30-33"
      },
      {
        "reference": "Genesis 34-36"
      },
      {
        "reference": "Genesis 37-39"
      },
      {
        "reference": "Genesis 40-42"
      },
      {
        "reference": "Genesis 43-46"
      },
      {
        "reference": "Genesis 47-49"
      },
      {
        "reference": "Genesis 50 · Exodus 1-2"
      },
      {
        "reference": "Exodus 3-5"
      },
      {
        "reference": "Exodus 6-9"
      },
      {
        "reference": "Exodus 10-12"
      },
      {
        "reference": "Exodus 13-15"
      },
      {
        "reference": "Exodus 16-18"
      },
      {
        "reference": "Exodus 19-22"
      },
      {
        "reference": "Exodus 23-25"
      },
      {
        "reference": "Exodus 26-28"
      },
      {
        "reference": "Exodus 29-31"
      },
      {
        "reference": "Exodus 32-35"
      },
      {
        "reference": "Exodus 36-38"
      },
      {
        "reference": "Exodus 39-40 · Leviticus 1"
      },
      {
        "reference": "Leviticus 2-4"
      },
      {
        "reference": "Leviticus 5-8"
      },
      {
        "reference": "Leviticus 9-11"
      },
      {
        "reference": "Leviticus 12-14"
      },
      {
        "reference": "Leviticus 15-17"
      },
      {
        "reference": "Leviticus 18-21"
      },
      {
        "reference": "Leviticus 22-24"
      },
      {
        "reference": "Leviticus 25-27"
      },
      {
        "reference": "Numbers 1-4"
      },
      {
        "reference": "Numbers 5-7"
      },
      {
        "reference": "Numbers 8-10"
      },
      {
        "reference": "Numbers 11-13"
      },
      {
        "reference": "Numbers 14-17"
      },
      {
        "reference": "Numbers 18-20"
      },
      {
        "reference": "Numbers 21-23"
      },
      {
        "reference": "Numbers 24-26"
      },
      {
        "reference": "Numbers 27-30"
      },
      {
        "reference": "Numbers 31-33"
      },
      {
        "reference": "Numbers 34-36"
      },
      {
        "reference": "Deuteronomy 1-3"
      },
      {
        "reference": "Deuteronomy 4-7"
      },
      {
        "reference": "Deuteronomy 8-10"
      },
      {
        "reference": "Deuteronomy 11-13"
      },
      {
        "reference": "Deuteronomy 14-16"
      },
      {
        "reference": "Deuteronomy 17-20"
      },
      {
        "reference": "Deuteronomy 21-23"
      },
      {
        "reference": "Deuteronomy 24-26"
      },
      {
        "reference": "Deuteronomy 27-29"
      },
      {
        "reference": "Deuteronomy 30-33"
      },
      {
        "reference": "Deuteronomy 34 · Joshua 1-2"
      },
      {
        "reference": "Joshua 3-5"
      },
      {
        "reference": "Joshua 6-8"
      },
      {
        "reference": "Joshua 9-12"
      },
      {
        "reference": "Joshua 13-15"
      },
      {
        "reference": "Joshua 16-18"
      },
      {
        "reference": "Joshua 19-21"
      },
      {
        "reference": "Joshua 22-24 · Judges 1"
      },
      {
        "reference": "Judges 2-4"
      },
      {
        "reference": "Judges 5-7"
      },
      {
        "reference": "Judges 8-11"
      },
      {
        "reference": "Judges 12-14"
      },
      {
        "reference": "Judges 15-17"
      },
      {
        "reference": "Judges 18-20"
      },
      {
        "reference": "Judges 21 · Ruth 1-3"
      },
      {
        "reference": "Ruth 4 · 1 Samuel 1-2"
      },
      {
        "reference": "1 Samuel 3-5"
      },
      {
        "reference": "1 Samuel 6-8"
      },
      {
        "reference": "1 Samuel 9-12"
      },
      {
        "reference": "1 Samuel 13-15"
      },
      {
        "reference": "1 Samuel 16-18"
      },
      {
        "reference": "1 Samuel 19-21"
      },
      {
        "reference": "1 Samuel 22-25"
      },
      {
        "reference": "1 Samuel 26-28"
      },
      {
        "reference": "1 Samuel 29-31"
      },
      {
        "reference": "2 Samuel 1-3"
      },
      {
        "reference": "2 Samuel 4-7"
      },
      {
        "reference": "2 Samuel 8-10"
      },
      {
        "reference": "2 Samuel 11-13"
      },
      {
        "reference": "2 Samuel 14-16"
      },
      {
        "reference": "2 Samuel 17-20"
      },
      {
        "reference": "2 Samuel 21-23"
      },
      {
        "reference": "2 Samuel 24 · 1 Kings 1-2"
      },
      {
        "reference": "1 Kings 3-5"
      },
      {
        "reference": "1 Kings 6-9"
      },
      {
        "reference": "1 Kings 10-12"
      },
      {
        "reference": "1 Kings 13-15"
      },
      {
        "reference": "1 Kings 16-18"
      },
      {
        "reference": "1 Kings 19-22"
      },
      {
        "reference": "2 Kings 1-3"
      },
      {
        "reference": "2 Kings 4-6"
      },
      {
        "reference": "2 Kings 7-9"
      },
      {
        "reference": "2 Kings 10-13"
      },
      {
        "reference": "2 Kings 14-16"
      },
      {
        "reference": "2 Kings 17-19"
      },
      {
        "reference": "2 Kings 20-23"
      },
      {
        "reference": "2 Kings 24-25 · 1 Chronicles 1"
      },
      {
        "reference": "1 Chronicles 2-4"
      },
      {
        "reference": "1 Chronicles 5-7"
      },
      {
        "reference": "1 Chronicles 8-11"
      },
      {
        "reference": "1 Chronicles 12-14"
      },
      {
        "reference": "1 Chronicles 15-17"
      },
      {
        "reference": "1 Chronicles 18-20"
      },
      {
        "reference": "1 Chronicles 21-24"
      },
      {
        "reference": "1 Chronicles 25-27"
      },
      {
        "reference": "1 Chronicles 28-29 · 2 Chronicles 1"
      },
      {
        "reference": "2 Chronicles 2-4"
      },
      {
        "reference": "2 Chronicles 5-8"
      },
      {
        "reference": "2 Chronicles 9-11"
      },
      {
        "reference": "2 Chronicles 12-14"
      },
      {
        "reference": "2 Chronicles 15-17"
      },
      {
        "reference": "2 Chronicles 18-21"
      },
      {
        "reference": "2 Chronicles 22-24"
      },
      {
        "reference": "2 Chronicles 25-27"
      },
      {
        "reference": "2 Chronicles 28-30"
      },
      {
        "reference": "2 Chronicles 31-34"
      },
      {
        "reference": "2 Chronicles 35-36 · Ezra 1"
      },
      {
        "reference": "Ezra 2-4"
      },
      {
        "reference": "Ezra 5-7"
      },
      {
        "reference": "Ezra 8-10 · Nehemiah 1"
      },
      {
        "reference": "Nehemiah 2-4"
      },
      {
        "reference": "Nehemiah 5-7"
      },
      {
        "reference": "Nehemiah 8-10"
      },
      {
        "reference": "Nehemiah 11-13 · Esther 1"
      },
      {
        "reference": "Esther 2-4"
      },
      {
        "reference": "Esther 5-7"
      },
      {
        "reference": "Esther 8-10 · Job 1"
      },
      {
        "reference": "Job 2-4"
      },
      {
        "reference": "Job 5-7"
      },
      {
        "reference": "Job 8-10"
      },
      {
        "reference": "Job 11-14"
      },
      {
        "reference": "Job 15-17"
      },
      {
        "reference": "Job 18-20"
      },
      {
        "reference": "Job 21-23"
      },
      {
        "reference": "Job 24-27"
      },
      {
        "reference": "Job 28-30"
      },
      {
        "reference": "Job 31-33"
      },
      {
        "reference": "Job 34-36"
      },
      {
        "reference": "Job 37-40"
      },
      {
        "reference": "Job 41-42 · Psalms 1"
      },
      {
        "reference": "Psalms 2-4"
      },
      {
        "reference": "Psalms 5-7"
      },
      {
        "reference": "Psalms 8-11"
      },
      {
        "reference": "Psalms 12-14"
      },
      {
        "reference": "Psalms 15-17"
      },
      {
        "reference": "Psalms 18-20"
      },
      {
        "reference": "Psalms 21-24"
      },
      {
        "reference": "Psalms 25-27"
      },
      {
        "reference": "Psalms 28-30"
      },
      {
        "reference": "Psalms 31-33"
      },
      {
        "reference": "Psalms 34-37"
      },
      {
        "reference": "Psalms 38-40"
      },
      {
        "reference": "Psalms 41-43"
      },
      {
        "reference": "Psalms 44-46"
      },
      {
        "reference": "Psalms 47-50"
      },
      {
        "reference": "Psalms 51-53"
      },
      {
        "reference": "Psalms 54-56"
      },
      {
        "reference": "Psalms 57-59"
      },
      {
        "reference": "Psalms 60-63"
      },
      {
        "reference": "Psalms 64-66"
      },
      {
        "reference": "Psalms 67-69"
      },
      {
        "reference": "Psalms 70-73"
      },
      {
        "reference": "Psalms 74-76"
      },
      {
        "reference": "Psalms 77-79"
      },
      {
        "reference": "Psalms 80-82"
      },
      {
        "reference": "Psalms 83-86"
      },
      {
        "reference": "Psalms 87-89"
      },
      {
        "reference": "Psalms 90-92"
      },
      {
        "reference": "Psalms 93-95"
      },
      {
        "reference": "Psalms 96-99"
      },
      {
        "reference": "Psalms 100-102"
      },
      {
        "reference": "Psalms 103-105"
      },
      {
        "reference": "Psalms 106-108"
      },
      {
        "reference": "Psalms 109-112"
      },
      {
        "reference": "Psalms 113-115"
      },
      {
        "reference": "Psalms 116-118"
      },
      {
        "reference": "Psalms 119-121"
      },
      {
        "reference": "Psalms 122-125"
      },
      {
        "reference": "Psalms 126-128"
      },
      {
        "reference": "Psalms 129-131"
      },
      {
        "reference": "Psalms 132-134"
      },
      {
        "reference": "Psalms 135-138"
      },
      {
        "reference": "Psalms 139-141"
      },
      {
        "reference": "Psalms 142-144"
      },
      {
        "reference": "Psalms 145-147"
      },
      {
        "reference": "Psalms 148-150 · Proverbs 1"
      },
      {
        "reference": "Proverbs 2-4"
      },
      {
        "reference": "Proverbs 5-7"
      },
      {
        "reference": "Proverbs 8-10"
      },
      {
        "reference": "Proverbs 11-14"
      },
      {
        "reference": "Proverbs 15-17"
      },
      {
        "reference": "Proverbs 18-20"
      },
      {
        "reference": "Proverbs 21-24"
      },
      {
        "reference": "Proverbs 25-27"
      },
      {
        "reference": "Proverbs 28-30"
      },
      {
        "reference": "Proverbs 31 · Ecclesiastes 1-2"
      },
      {
        "reference": "Ecclesiastes 3-6"
      },
      {
        "reference": "Ecclesiastes 7-9"
      },
      {
        "reference": "Ecclesiastes 10-12"
      },
      {
        "reference": "Song of Solomon 1-3"
      },
      {
        "reference": "Song of Solomon 4-7"
      },
      {
        "reference": "Song of Solomon 8 · Isaiah 1-2"
      },
      {
        "reference": "Isaiah 3-5"
      },
      {
        "reference": "Isaiah 6-8"
      },
      {
        "reference": "Isaiah 9-12"
      },
      {
        "reference": "Isaiah 13-15"
      },
      {
        "reference": "Isaiah 16-18"
      },
      {
        "reference": "Isaiah 19-21"
      },
      {
        "reference": "Isaiah 22-25"
      },
      {
        "reference": "Isaiah 26-28"
      },
      {
        "reference": "Isaiah 29-31"
      },
      {
        "reference": "Isaiah 32-34"
      },
      {
        "reference": "Isaiah 35-38"
      },
      {
        "reference": "Isaiah 39-41"
      },
      {
        "reference": "Isaiah 42-44"
      },
      {
        "reference": "Isaiah 45-47"
      },
      {
        "reference": "Isaiah 48-51"
      },
      {
        "reference": "Isaiah 52-54"
      },
      {
        "reference": "Isaiah 55-57"
      },
      {
        "reference": "Isaiah 58-60"
      },
      {
        "reference": "Isaiah 61-64"
      },
      {
        "reference": "Isaiah 65-66 · Jeremiah 1"
      },
      {
        "reference": "Jeremiah 2-4"
      },
      {
        "reference": "Jeremiah 5-7"
      },
      {
        "reference": "Jeremiah 8-11"
      },
      {
        "reference": "Jeremiah 12-14"
      },
      {
        "reference": "Jeremiah 15-17"
      },
      {
        "reference": "Jeremiah 18-21"
      },
      {
        "reference": "Jeremiah 22-24"
      },
      {
        "reference": "Jeremiah 25-27"
      },
      {
        "reference": "Jeremiah 28-30"
      },
      {
        "reference": "Jeremiah 31-34"
      },
      {
        "reference": "Jeremiah 35-37"
      },
      {
        "reference": "Jeremiah 38-40"
      },
      {
        "reference": "Jeremiah 41-43"
      },
      {
        "reference": "Jeremiah 44-47"
      },
      {
        "reference": "Jeremiah 48-50"
      },
      {
        "reference": "Jeremiah 51-52 · Lamentations 1"
      },
      {
        "reference": "Lamentations 2-4"
      },
      {
        "reference": "Lamentations 5 · Ezekiel 1-3"
      },
      {
        "reference": "Ezekiel 4-6"
      },
      {
        "reference": "Ezekiel 7-9"
      },
      {
        "reference": "Ezekiel 10-12"
      },
      {
        "reference": "Ezekiel 13-16"
      },
      {
        "reference": "Ezekiel 17-19"
      },
      {
        "reference": "Ezekiel 20-22"
      },
      {
        "reference": "Ezekiel 23-25"
      },
      {
        "reference": "Ezekiel 26-29"
      },
      {
        "reference": "Ezekiel 30-32"
      },
      {
        "reference": "Ezekiel 33-35"
      },
      {
        "reference": "Ezekiel 36-38"
      },
      {
        "reference": "Ezekiel 39-42"
      },
      {
        "reference": "Ezekiel 43-45"
      },
      {
        "reference": "Ezekiel 46-48"
      },
      {
        "reference": "Daniel 1-3"
      },
      {
        "reference": "Daniel 4-7"
      },
      {
        "reference": "Daniel 8-10"
      },
      {
        "reference": "Daniel 11-12 · Hosea 1"
      },
      {
        "reference": "Hosea 2-5"
      },
      {
        "reference": "Hosea 6-8"
      },
      {
        "reference": "Hosea 9-11"
      },
      {
        "reference": "Hosea 12-14"
      },
      {
        "reference": "Joel 1-3 · Amos 1"
      },
      {
        "reference": "Amos 2-4"
      },
      {
        "reference": "Amos 5-7"
      },
      {
        "reference": "Amos 8-9 · Obadiah 1"
      },
      {
        "reference": "Jonah 1-4"
      },
      {
        "reference": "Micah 1-3"
      },
      {
        "reference": "Micah 4-6"
      },
      {
        "reference": "Micah 7 · Nahum 1-2"
      },
      {
        "reference": "Nahum 3 · Habakkuk 1-3"
      },
      {
        "reference": "Zephaniah 1-3"
      },
      {
        "reference": "Haggai 1-2 · Zechariah 1"
      },
      {
        "reference": "Zechariah 2-4"
      },
      {
        "reference": "Zechariah 5-8"
      },
      {
        "reference": "Zechariah 9-11"
      },
      {
        "reference": "Zechariah 12-14"
      },
      {
        "reference": "Malachi 1-3"
      },
      {
        "reference": "Malachi 4 · Matthew 1-3"
      },
      {
        "reference": "Matthew 4-6"
      },
      {
        "reference": "Matthew 7-9"
      },
      {
        "reference": "Matthew 10-12"
      },
      {
        "reference": "Matthew 13-16"
      },
      {
        "reference": "Matthew 17-19"
      },
      {
        "reference": "Matthew 20-22"
      },
      {
        "reference": "Matthew 23-25"
      },
      {
        "reference": "Matthew 26-28 · Mark 1"
      },
      {
        "reference": "Mark 2-4"
      },
      {
        "reference": "Mark 5-7"
      },
      {
        "reference": "Mark 8-10"
      },
      {
        "reference": "Mark 11-14"
      },
      {
        "reference": "Mark 15-16 · Luke 1"
      },
      {
        "reference": "Luke 2-4"
      },
      {
        "reference": "Luke 5-8"
      },
      {
        "reference": "Luke 9-11"
      },
      {
        "reference": "Luke 12-14"
      },
      {
        "reference": "Luke 15-17"
      },
      {
        "reference": "Luke 18-21"
      },
      {
        "reference": "Luke 22-24"
      },
      {
        "reference": "John 1-3"
      },
      {
        "reference": "John 4-6"
      },
      {
        "reference": "John 7-10"
      },
      {
        "reference": "John 11-13"
      },
      {
        "reference": "John 14-16"
      },
      {
        "reference": "John 17-19"
      },
      {
        "reference": "John 20-21 · Acts 1-2"
      },
      {
        "reference": "Acts 3-5"
      },
      {
        "reference": "Acts 6-8"
      },
      {
        "reference": "Acts 9-11"
      },
      {
        "reference": "Acts 12-15"
      },
      {
        "reference": "Acts 16-18"
      },
      {
        "reference": "Acts 19-21"
      },
      {
        "reference": "Acts 22-24"
      },
      {
        "reference": "Acts 25-28"
      },
      {
        "reference": "Romans 1-3"
      },
      {
        "reference": "Romans 4-6"
      },
      {
        "reference": "Romans 7-9"
      },
      {
        "reference": "Romans 10-13"
      },
      {
        "reference": "Romans 14-16"
      },
      {
        "reference": "1 Corinthians 1-3"
      },
      {
        "reference": "1 Corinthians 4-6"
      },
      {
        "reference": "1 Corinthians 7-10"
      },
      {
        "reference": "1 Corinthians 11-13"
      },
      {
        "reference": "1 Corinthians 14-16"
      },
      {
        "reference": "2 Corinthians 1-4"
      },
      {
        "reference": "2 Corinthians 5-7"
      },
      {
        "reference": "2 Corinthians 8-10"
      },
      {
        "reference": "2 Corinthians 11-13"
      },
      {
        "reference": "Galatians 1-4"
      },
      {
        "reference": "Galatians 5-6 · Ephesians 1"
      },
      {
        "reference": "Ephesians 2-4"
      },
      {
        "reference": "Ephesians 5-6 · Philippians 1"
      },
      {
        "reference": "Philippians 2-4 · Colossians 1"
      },
      {
        "reference": "Colossians 2-4"
      },
      {
        "reference": "1 Thessalonians 1-3"
      },
      {
        "reference": "1 Thessalonians 4-5 · 2 Thessalonians 1"
      },
      {
        "reference": "2 Thessalonians 2-3 · 1 Timothy 1-2"
      },
      {
        "reference": "1 Timothy 3-5"
      },
      {
        "reference": "1 Timothy 6 · 2 Timothy 1-2"
      },
      {
        "reference": "2 Timothy 3-4 · Titus 1"
      },
      {
        "reference": "Titus 2-3 · Philemon 1 · Hebrews 1"
      },
      {
        "reference": "Hebrews 2-4"
      },
      {
        "reference": "Hebrews 5-7"
      },
      {
        "reference": "Hebrews 8-10"
      },
      {
        "reference": "Hebrews 11-13 · James 1"
      },
      {
        "reference": "James 2-4"
      },
      {
        "reference": "James 5 · 1 Peter 1-2"
      },
      {
        "reference": "1 Peter 3-5"
      },
      {
        "reference": "2 Peter 1-3 · 1 John 1"
      },
      {
        "reference": "1 John 2-4"
      },
      {
        "reference": "1 John 5 · 2 John 1 · 3 John 1"
      },
      {
        "reference": "Jude 1 · Revelation 1-2"
      },
      {
        "reference": "Revelation 3-6"
      },
      {
        "reference": "Revelation 7-9"
      },
      {
        "reference": "Revelation 10-12"
      },
      {
        "reference": "Revelation 13-15"
      },
      {
        "reference": "Revelation 16-19"
      },
      {
        "reference": "Revelation 20-22"
      }
    ]
  }
];
