/**
 * Builds the offline KJV bundle used by the Bible tab.
 *
 *   node scripts/build-bible.mjs
 *
 * Source: https://github.com/thiagobodruk/bible (en_kjv.json) — Public Domain.
 * Output:
 *   assets/bible/kjv/<bookId>.json   one file per book: [[ch1 verses], [ch2 verses], ...]
 *   constants/bible-books.ts         generated metadata for all 66 books
 *
 * Re-run this only when you want to refresh the bundled text.
 */

import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_URL = 'https://raw.githubusercontent.com/thiagobodruk/bible/master/json/en_kjv.json';
const outDir = path.join(root, 'assets', 'bible', 'kjv');

/** source abbrev -> [appId, display name, testament] */
const BOOK_MAP = {
  gn: ['gen', 'Genesis', 'OT'],      ex: ['exo', 'Exodus', 'OT'],
  lv: ['lev', 'Leviticus', 'OT'],    nm: ['num', 'Numbers', 'OT'],
  dt: ['deu', 'Deuteronomy', 'OT'],  js: ['jos', 'Joshua', 'OT'],
  jud: ['jdg', 'Judges', 'OT'],      rt: ['rut', 'Ruth', 'OT'],
  '1sm': ['1sa', '1 Samuel', 'OT'],  '2sm': ['2sa', '2 Samuel', 'OT'],
  '1kgs': ['1ki', '1 Kings', 'OT'],  '2kgs': ['2ki', '2 Kings', 'OT'],
  '1ch': ['1ch', '1 Chronicles', 'OT'], '2ch': ['2ch', '2 Chronicles', 'OT'],
  ezr: ['ezr', 'Ezra', 'OT'],        ne: ['neh', 'Nehemiah', 'OT'],
  et: ['est', 'Esther', 'OT'],       job: ['job', 'Job', 'OT'],
  ps: ['psa', 'Psalms', 'OT'],       prv: ['pro', 'Proverbs', 'OT'],
  ec: ['ecc', 'Ecclesiastes', 'OT'], so: ['sng', 'Song of Solomon', 'OT'],
  is: ['isa', 'Isaiah', 'OT'],       jr: ['jer', 'Jeremiah', 'OT'],
  lm: ['lam', 'Lamentations', 'OT'], ez: ['ezk', 'Ezekiel', 'OT'],
  dn: ['dan', 'Daniel', 'OT'],       ho: ['hos', 'Hosea', 'OT'],
  jl: ['jol', 'Joel', 'OT'],         am: ['amo', 'Amos', 'OT'],
  ob: ['oba', 'Obadiah', 'OT'],      jn: ['jon', 'Jonah', 'OT'],
  mi: ['mic', 'Micah', 'OT'],        na: ['nam', 'Nahum', 'OT'],
  hk: ['hab', 'Habakkuk', 'OT'],     zp: ['zep', 'Zephaniah', 'OT'],
  hg: ['hag', 'Haggai', 'OT'],       zc: ['zec', 'Zechariah', 'OT'],
  ml: ['mal', 'Malachi', 'OT'],

  mt: ['mat', 'Matthew', 'NT'],      mk: ['mrk', 'Mark', 'NT'],
  lk: ['luk', 'Luke', 'NT'],         jo: ['jhn', 'John', 'NT'],
  act: ['act', 'Acts', 'NT'],        rm: ['rom', 'Romans', 'NT'],
  '1co': ['1co', '1 Corinthians', 'NT'], '2co': ['2co', '2 Corinthians', 'NT'],
  gl: ['gal', 'Galatians', 'NT'],    eph: ['eph', 'Ephesians', 'NT'],
  ph: ['phi', 'Philippians', 'NT'],  cl: ['col', 'Colossians', 'NT'],
  '1ts': ['1th', '1 Thessalonians', 'NT'], '2ts': ['2th', '2 Thessalonians', 'NT'],
  '1tm': ['1ti', '1 Timothy', 'NT'], '2tm': ['2ti', '2 Timothy', 'NT'],
  tt: ['tit', 'Titus', 'NT'],        phm: ['phm', 'Philemon', 'NT'],
  hb: ['heb', 'Hebrews', 'NT'],      jm: ['jas', 'James', 'NT'],
  '1pe': ['1pe', '1 Peter', 'NT'],   '2pe': ['2pe', '2 Peter', 'NT'],
  '1jo': ['1jn', '1 John', 'NT'],    '2jo': ['2jn', '2 John', 'NT'],
  '3jo': ['3jn', '3 John', 'NT'],    jd: ['jud', 'Jude', 'NT'],
  re: ['rev', 'Revelation', 'NT'],
};

/** KJV wraps translator-supplied words in braces; drop the markers, keep the words. */
function clean(text) {
  return String(text)
    .replace(/[{}]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

async function loadSource() {
  const local = process.argv[2];
  if (local) {
    console.log(`Reading local source: ${local}`);
    return readFile(local, 'utf8');
  }
  console.log(`Downloading ${SOURCE_URL} …`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`Download failed: ${res.status} ${res.statusText}`);
  return res.text();
}

async function main() {
  const raw = (await loadSource()).replace(/^﻿/, '');
  const source = JSON.parse(raw);

  if (source.length !== 66) {
    throw new Error(`Expected 66 books in source, got ${source.length}`);
  }

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const books = [];
  let totalChapters = 0;
  let totalVerses = 0;

  for (const entry of source) {
    const mapped = BOOK_MAP[entry.abbrev];
    if (!mapped) throw new Error(`Unmapped book abbrev: ${entry.abbrev}`);
    const [id, name, testament] = mapped;

    const chapters = entry.chapters.map((verses) => verses.map(clean));
    totalChapters += chapters.length;
    totalVerses += chapters.reduce((sum, c) => sum + c.length, 0);

    await writeFile(path.join(outDir, `${id}.json`), JSON.stringify(chapters), 'utf8');
    books.push({ id, name, chapters: chapters.length, testament });
  }

  const header = `// GENERATED by scripts/build-bible.mjs — do not edit by hand.
// Source: ${SOURCE_URL} (King James Version, Public Domain)
// ${books.length} books · ${totalChapters} chapters · ${totalVerses} verses

export type Testament = 'OT' | 'NT';

export type BibleBook = {
  id: string;
  name: string;
  chapters: number;
  testament: Testament;
};

export const BIBLE_BOOKS: BibleBook[] = ${JSON.stringify(books, null, 2)};

export const BIBLE_BOOKS_BY_ID: Record<string, BibleBook> = Object.fromEntries(
  BIBLE_BOOKS.map((book) => [book.id, book])
);
`;

  await writeFile(path.join(root, 'constants', 'bible-books.ts'), header, 'utf8');

  // Lazy require map. Metro bundles every entry, but a book's JSON is only
  // parsed the first time its loader runs — so opening one book doesn't pay
  // the cost of all 66.
  const loaderLines = books
    .map((book) => `  '${book.id}': () => require('../assets/bible/kjv/${book.id}.json'),`)
    .join('\n');

  const offline = `// GENERATED by scripts/build-bible.mjs — do not edit by hand.
// Offline KJV text (Public Domain). Each entry is [chapter][verseIndex] => string.

type ChapterData = string[][];

const LOADERS: Record<string, () => ChapterData> = {
${loaderLines}
};

const cache = new Map<string, ChapterData>();

function loadBook(bookId: string): ChapterData | null {
  const cached = cache.get(bookId);
  if (cached) return cached;

  const loader = LOADERS[bookId];
  if (!loader) return null;

  const data = loader();
  cache.set(bookId, data);
  return data;
}

/** Verse strings for a chapter, or null when the reference does not exist. */
export function getOfflineChapter(bookId: string, chapter: number): string[] | null {
  const book = loadBook(bookId);
  if (!book) return null;
  return book[chapter - 1] ?? null;
}

export function hasOfflineBook(bookId: string): boolean {
  return bookId in LOADERS;
}
`;

  await writeFile(path.join(root, 'constants', 'bible-offline.ts'), offline, 'utf8');

  console.log(`\nWrote ${books.length} book files to assets/bible/kjv/`);
  console.log(`  ${totalChapters} chapters, ${totalVerses} verses`);
  console.log('Wrote constants/bible-books.ts');
  console.log('Wrote constants/bible-offline.ts');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
